name: Build & Release PAR2cmd-turbo Binaries

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
    PAR2_VERSION: ${{ github.ref_name }}

jobs:
  build-and-release:
    runs-on: self-hosted
    if: startsWith(github.ref_name, 'v')

    steps:
      - name: Create necessary directories
        run: |
          apt update && apt install -y git
          mkdir -p binaries
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU emulation
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export per-arch binaries
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          outputs: ./binaries 
          build-args: |
            PAR2_VERSION=${{ github.ref_name }}
            LDFLAGS=-static -s

      - name: Package binaries for release
        run: |
          mkdir -p artifacts
          ls -la binaries/*
          sh -c 'find . -name par2\* -exec mv {} artifacts/ \;'

      - name: Create GitHub Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload assets to Release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: artifacts/*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
